### ISSUE TITLE
[FIX] social 정보 분리로 인한 테스트 실패 확인

### ISSUE THREAD

**Issue by hyeonic** [SKHUED-IN/skhuedin#164]
## 목적
> social 관련된 정보를 외부로 분리하던 중 테스트를 실행 할 때 해당하는 value 값들을 application.yml에서 찾을 수 없어 테스트가 실패하는 것을 확인

## 내용
- [ ] 테스트 전용 application.yml 수정

## 참고사항

**Comment by hyeonic** [comment]
![image](https://user-images.githubusercontent.com/59357153/121709303-60931080-cb13-11eb-8a07-c5124d020f1a.png)
개선 전

```
spring:
  console:
    enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

resources:
  # file:// 로 탐색되는 location
  location: /profile/
  # uri에서 handling 하기 위한 path
  uri_path: /profile

  # 각각 local 운영 체제에 맞추어 실제로 저장되는 저장소 위치를 설정
  storage_location: c:/profile/

social:
  naver:
    login: ""
    logout: ""
  kakao:
    login: ""
    logout: ""
  google:
    login: ""
    logout: ""
```
![image](https://user-images.githubusercontent.com/59357153/121709396-7accee80-cb13-11eb-9e35-bb357c045fdd.png)
개선 후
